apiVersion: v1
kind: Pod                 # Podに関する設定ファイルであることを指定
metadata:                 # メタデータに関する情報を指定
  name: httpd             # Podの名前を指定
  labels:                 # Podに付与するラベルを指定
    app: httpd
spec:
  containers:
  - name: httpd           # コンテナ名を指定
    image: httpd          # コンテナを作成する際に使用するイメージを指定
    ports:
    - containerPort: 80   # コンテナに外部からアクセスできるポートを指定
