apiVersion: v1
kind: Service         # Serviceの定義であることを指定
metadata:
  name: httpd         # Service名を指定
spec:
  type: NodePort
  ports:
    - port: 80        # Serviceが使用するポート番号を指定
  selector:           # 対象とするPodをラベルで指定
    app: httpd
